### PR TITLE
feat: TypeScript support for Collection

### PR DESCRIPTION
**Pull request by MunifTanjim**

### CODE REVIEW

**Comment by gr2m** [comment]
Oh that looks great, thank you for putting that together Munif! I'll test it with my @octokit libraries, which are all written with TypeScript and I use the collection API

**Comment by gr2m** [comment]
Very sorry Munif, I totally dropped the ball on this one. I'm looking into it now

**Review by gr2m — COMMENTED** [review]
Instead of using O, R, E, could you use something more clear, such as TOptions, TResult, TError?

Otherwise this is great, really appreciate the thorough docs updates!

**Comment by MunifTanjim** [comment]
> Instead of using O, R, E, could you use something more clear, such as TOptions, TResult, TError?

Just to clarify, you want to change the shape of the generic that `Hook.Collection` accepts, right?

So, instead of:

```ts
type HooksType = {
  add: { O: { type: string }; R: { id: number }; E: Error };
  save: { O: { type: string }; R: { id: number } };
  read: { O: { id: number; foo: number } };
  destroy: { O: { id: number; foo: string } };
};

const hooks = Hook.Collection<HooksType>();
```

You want this:

```ts
type HooksType = {
  add: { Options: { type: string }; Result: { id: number }; Error: Error };
  save: { Options: { type: string }; Result: { id: number } };
  read: { Options: { id: number; foo: number } };
  destroy: { Options: { id: number; foo: string } };
};

const hooks = Hook.Collection<HooksType>();
```

Do you think this going to be very verbose?

**Comment by MunifTanjim** [comment]
I've changed those to `Options`, `Result` and `Error` and updated the README to reflect that.

I've also kept the option to use `O`, `R`, `E` in case anybody prefers a shorter variant. But let me know if you don't want to keep that option, I'll remove them.

**Comment by gr2m** [comment]
It seems to be working while working in TypeScript, but currently my build step with `tsc` fails when trying to update `@octokit/core`.

The error I'm getting is 

```
➜  core.js git:(master) ✗ /Users/gregor/Projects/octokit/core.js/node_modules/typescript/bin/tsc --outDir /Users/gregor/Projects/octokit/core.js/pkg/dist-src/ -d --declarationDir /Users/gregor/Projects/octokit/core.js/pkg/dist-types/ --project /Users/gregor/Projects/octokit/core.js/tsconfig.json --target es2020 --module esnext --noEmit false --sourceMap false
src/index.ts:117:5 - error TS2322: Type 'HookCollection<Record<string, { O: any; R: any; E: any; }>, string>' is not assignable to type 'HookCollection<HookType, "request">'.
  Property 'request' is missing in type 'Record<string, { O: any; R: any; E: any; }>' but required in type 'HookType'.
```

any idea what that could be?

**Comment by MunifTanjim** [comment]
You probably forgot to pass the type on `line 117`. It should be:

```ts
    // 117
    const hook = new Collection<HookType>()
```

otherwise TypeScript won't let you assign it to:

```ts
  // 178
  hook: HookCollection<HookType>
```

P.S: You can omit the second generic type from `HookCollection<HookType, "request">`. TypeScript will automatically derive it from `HookType`.

**Comment by gr2m** [comment]
> You probably forgot to pass the type on [`line 73`](https://github.com/octokit/core.js/blob/337215c8517dd5f845555a1f97c763c60d3f479d/src/index.ts#L73). It should be:
> 
> ```ts
>     const hook = new Collection<HookType>()
> ```

That was _exactly_ it. Thank you so much!

**Comment by gr2m** [comment]
One last question. I think this change is breaking for TypeScript users of the `HookCollection` type. It seems that a type parameter is now required.

```
src/index.ts(178,9): error TS2707: Generic type 'HookCollection<HooksType, HookName>' requires between 1 and 2 type arguments
```

Is there a simple way to workaround that? No worries if not, I don't consider type-only changes breaking changes, but if it's simple enough, I think it would reduce some friction when people upgrade

**Comment by MunifTanjim** [comment]
> Is there a simple way to workaround that?

Sure. Making it required was not intentional. Fixed it.

**Comment by gr2m** [comment]
Sorry @MunifTanjim, I've upgraded `@octokit/core` without locally without making any code changes, but am now getting a different build error:

```
/Users/gregor/Projects/octokit/core.js/node_modules/typescript/bin/tsc --outDir /Users/gregor/Projects/octokit/core.js/pkg/dist-src/ -d --declarationDir /Users/gregor/Projects/octokit/core.js/pkg/dist-types/ --project /Users/gregor/Projects/octokit/core.js/tsconfig.json --target es2020 --module esnext --noEmit false --sourceMap false
src/index.ts:117:5 - error TS2322: Type 'HookCollection<Record<string, { O: any; R: any; E: any; }>, string>' is not assignable to type 'HookCollection<Record<string, { Options: any; Result: any; Error: any; }>, string>'.
  Type 'Record<string, { O: any; R: any; E: any; }>' is not assignable to type 'Record<string, { Options: any; Result: any; Error: any; }>'.
    Index signatures are incompatible.
      Type '{ O: any; R: any; E: any; }' is not assignable to type '{ Options: any; Result: any; Error: any; }'.

117     this.hook = hook;
        ~~~~~~~~~
```

Sounds like an incompatibility with the type parameter names?

**Comment by MunifTanjim** [comment]
Sorry, was my bad. Missed a spot while making the type args optional.

**Comment by gr2m** [comment]
That was it, seems all to be working great now!

**Review by gr2m — APPROVED** [review]
Thank you so much, this is really great!

**Pull request merged**
